CREATE TABLE IF NOT EXISTS anti_bot_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    event_time DATETIME NOT NULL,
    account_id INT NOT NULL,
    char_id INT NOT NULL,
    char_name VARCHAR(24) NOT NULL,
    class_id INT NOT NULL,
    event_type VARCHAR(16) NOT NULL,
    map_name VARCHAR(32) NOT NULL,
    x SMALLINT NULL,
    y SMALLINT NULL,
    target_id INT NULL,
    target_type VARCHAR(16) NULL,
    target_class INT NULL,
    skill_id INT NULL,
    skill_lv SMALLINT NULL,
    item_id INT NULL,
    nearby_players SMALLINT NOT NULL DEFAULT 0,
    mode_tag VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    PRIMARY KEY (id),
    INDEX idx_event_time (event_time),
    INDEX idx_char_time (char_id, event_time),
    INDEX idx_event_type_time (event_type, event_time),
    INDEX idx_skill_time (skill_id, event_time),
    INDEX idx_target_class_time (target_class, event_time)
);